version: '2'
volumes:
  settings:
  nginx-data:
  nginx-logs:
networks:
  tunnel:
services:
  nginx:
    build: ./nginx
    privileged: true
    restart: 'unless-stopped'
    volumes:
      - nginx-data:/etc/letsencrypt
      - nginx-logs:/logs
    ports:
      - "80:80"
      - "443:443"
    networks:
      - tunnel
  cloudflared:
    build: ./cloudflared
    networks:
      - tunnel
  browser:
    build: ./browser
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    ports:
        - '5011' # management API (optional)
        - '35173:35173' # Chromium debugging port (optional)
        - '35174:35174' # Chromium debugging port (optional)
    volumes:
      - 'settings:/data' # Only required if using PERSISTENT flag (see below)i
  scheduler:
    restart: always
    build: ./scheduler
    privileged: true
    devices:
      - "/dev/cec0:/dev/cec0"
  yearly-calendar:
    restart: always
    build: ./yearly-calendar
    ports:
      - "3000:3000"
